//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using CPC.Helper;
using CPC.POS.Database;
using CPC.Toolkit.Base;

namespace CPC.POS.Model
{
    /// <summary>
    /// Model for table base_GuestReward
    /// </summary>
    [Serializable]
    public partial class base_GuestRewardModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_GuestRewardModel()
        {
            this.IsNew = true;
            this.base_GuestReward = new base_GuestReward();
        }

        // Default constructor that set entity to field
        public base_GuestRewardModel(base_GuestReward base_guestreward, bool isRaiseProperties = false)
        {
            this.base_GuestReward = base_guestreward;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_GuestReward base_GuestReward { get; private set; }

        #endregion

        #region Primitive Properties

        protected long _id;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Id</param>
        /// </summary>
        public long Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected long _guestId;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the GuestId</param>
        /// </summary>
        public long GuestId
        {
            get { return this._guestId; }
            set
            {
                if (this._guestId != value)
                {
                    this.IsDirty = true;
                    this._guestId = value;
                    OnPropertyChanged(() => GuestId);
                    PropertyChangedCompleted(() => GuestId);
                }
            }
        }

        protected int _rewardId;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the RewardId</param>
        /// </summary>
        public int RewardId
        {
            get { return this._rewardId; }
            set
            {
                if (this._rewardId != value)
                {
                    this.IsDirty = true;
                    this._rewardId = value;
                    OnPropertyChanged(() => RewardId);
                    PropertyChangedCompleted(() => RewardId);
                }
            }
        }

        protected decimal _amount;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Amount</param>
        /// </summary>
        public decimal Amount
        {
            get { return this._amount; }
            set
            {
                if (this._amount != value)
                {
                    this.IsDirty = true;
                    this._amount = value;
                    OnPropertyChanged(() => Amount);
                    PropertyChangedCompleted(() => Amount);
                }
            }
        }

        protected bool _isApply;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the IsApply</param>
        /// </summary>
        public bool IsApply
        {
            get { return this._isApply; }
            set
            {
                if (this._isApply != value)
                {
                    this.IsDirty = true;
                    this._isApply = value;
                    OnPropertyChanged(() => IsApply);
                    PropertyChangedCompleted(() => IsApply);
                }
            }
        }

        protected Nullable<System.DateTime> _earnedDate;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the EarnedDate</param>
        /// </summary>
        public Nullable<System.DateTime> EarnedDate
        {
            get { return this._earnedDate; }
            set
            {
                if (this._earnedDate != value)
                {
                    this.IsDirty = true;
                    this._earnedDate = value;
                    OnPropertyChanged(() => EarnedDate);
                    PropertyChangedCompleted(() => EarnedDate);
                }
            }
        }

        protected Nullable<System.DateTime> _appliedDate;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the AppliedDate</param>
        /// </summary>
        public Nullable<System.DateTime> AppliedDate
        {
            get { return this._appliedDate; }
            set
            {
                if (this._appliedDate != value)
                {
                    this.IsDirty = true;
                    this._appliedDate = value;
                    OnPropertyChanged(() => AppliedDate);
                    PropertyChangedCompleted(() => AppliedDate);
                }
            }
        }

        protected decimal _rewardValue;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the RewardValue</param>
        /// </summary>
        public decimal RewardValue
        {
            get { return this._rewardValue; }
            set
            {
                if (this._rewardValue != value)
                {
                    this.IsDirty = true;
                    this._rewardValue = value;
                    OnPropertyChanged(() => RewardValue);
                    PropertyChangedCompleted(() => RewardValue);
                }
            }
        }

        protected string _saleOrderResource;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the SaleOrderResource</param>
        /// </summary>
        public string SaleOrderResource
        {
            get { return this._saleOrderResource; }
            set
            {
                if (this._saleOrderResource != value)
                {
                    this.IsDirty = true;
                    this._saleOrderResource = value;
                    OnPropertyChanged(() => SaleOrderResource);
                    PropertyChangedCompleted(() => SaleOrderResource);
                }
            }
        }

        protected string _saleOrderNo;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the SaleOrderNo</param>
        /// </summary>
        public string SaleOrderNo
        {
            get { return this._saleOrderNo; }
            set
            {
                if (this._saleOrderNo != value)
                {
                    this.IsDirty = true;
                    this._saleOrderNo = value;
                    OnPropertyChanged(() => SaleOrderNo);
                    PropertyChangedCompleted(() => SaleOrderNo);
                }
            }
        }

        protected string _remark;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Remark</param>
        /// </summary>
        public string Remark
        {
            get { return this._remark; }
            set
            {
                if (this._remark != value)
                {
                    this.IsDirty = true;
                    this._remark = value;
                    OnPropertyChanged(() => Remark);
                    PropertyChangedCompleted(() => Remark);
                }
            }
        }

        protected Nullable<System.DateTime> _activedDate;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the ActivedDate</param>
        /// </summary>
        public Nullable<System.DateTime> ActivedDate
        {
            get { return this._activedDate; }
            set
            {
                if (this._activedDate != value)
                {
                    this.IsDirty = true;
                    this._activedDate = value;
                    OnPropertyChanged(() => ActivedDate);
                    PropertyChangedCompleted(() => ActivedDate);
                }
            }
        }

        protected Nullable<System.DateTime> _expireDate;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the ExpireDate</param>
        /// </summary>
        public Nullable<System.DateTime> ExpireDate
        {
            get { return this._expireDate; }
            set
            {
                if (this._expireDate != value)
                {
                    this.IsDirty = true;
                    this._expireDate = value;
                    OnPropertyChanged(() => ExpireDate);
                    PropertyChangedCompleted(() => ExpireDate);
                }
            }
        }

        protected string _reason;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Reason</param>
        /// </summary>
        public string Reason
        {
            get { return this._reason; }
            set
            {
                if (this._reason != value)
                {
                    this.IsDirty = true;
                    this._reason = value;
                    OnPropertyChanged(() => Reason);
                    PropertyChangedCompleted(() => Reason);
                }
            }
        }

        protected Nullable<short> _status;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Status</param>
        /// </summary>
        public Nullable<short> Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                    OnPropertyChanged(() => Status);
                    PropertyChangedCompleted(() => Status);
                }
            }
        }

        protected decimal _rewardSetupAmount;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the RewardSetupAmount</param>
        /// </summary>
        public decimal RewardSetupAmount
        {
            get { return this._rewardSetupAmount; }
            set
            {
                if (this._rewardSetupAmount != value)
                {
                    this.IsDirty = true;
                    this._rewardSetupAmount = value;
                    OnPropertyChanged(() => RewardSetupAmount);
                    PropertyChangedCompleted(() => RewardSetupAmount);
                }
            }
        }

        protected short _rewardSetupUnit;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the RewardSetupUnit</param>
        /// </summary>
        public short RewardSetupUnit
        {
            get { return this._rewardSetupUnit; }
            set
            {
                if (this._rewardSetupUnit != value)
                {
                    this.IsDirty = true;
                    this._rewardSetupUnit = value;
                    OnPropertyChanged(() => RewardSetupUnit);
                    PropertyChangedCompleted(() => RewardSetupUnit);
                }
            }
        }

        protected string _sign;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Sign</param>
        /// </summary>
        public string Sign
        {
            get { return this._sign; }
            set
            {
                if (this._sign != value)
                {
                    this.IsDirty = true;
                    this._sign = value;
                    OnPropertyChanged(() => Sign);
                    PropertyChangedCompleted(() => Sign);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <param>Public Method</param>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set PropertyModel to Entity</param>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_GuestReward.Id = this.Id;
            this.base_GuestReward.GuestId = this.GuestId;
            this.base_GuestReward.RewardId = this.RewardId;
            this.base_GuestReward.Amount = this.Amount;
            this.base_GuestReward.IsApply = this.IsApply;
            this.base_GuestReward.EarnedDate = this.EarnedDate;
            this.base_GuestReward.AppliedDate = this.AppliedDate;
            this.base_GuestReward.RewardValue = this.RewardValue;
            if (this.SaleOrderResource != null)
                this.base_GuestReward.SaleOrderResource = this.SaleOrderResource.Trim();
            if (this.SaleOrderNo != null)
                this.base_GuestReward.SaleOrderNo = this.SaleOrderNo.Trim();
            if (this.Remark != null)
                this.base_GuestReward.Remark = this.Remark.Trim();
            this.base_GuestReward.ActivedDate = this.ActivedDate;
            this.base_GuestReward.ExpireDate = this.ExpireDate;
            if (this.Reason != null)
                this.base_GuestReward.Reason = this.Reason.Trim();
            this.base_GuestReward.Status = this.Status;
            this.base_GuestReward.RewardSetupAmount = this.RewardSetupAmount;
            this.base_GuestReward.RewardSetupUnit = this.RewardSetupUnit;
            if (this.Sign != null)
                this.base_GuestReward.Sign = this.Sign.Trim();
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set Entity to PropertyModel</param>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_GuestReward.Id;
            this._guestId = this.base_GuestReward.GuestId;
            this._rewardId = this.base_GuestReward.RewardId;
            this._amount = this.base_GuestReward.Amount;
            this._isApply = this.base_GuestReward.IsApply;
            this._earnedDate = this.base_GuestReward.EarnedDate;
            this._appliedDate = this.base_GuestReward.AppliedDate;
            this._rewardValue = this.base_GuestReward.RewardValue;
            this._saleOrderResource = this.base_GuestReward.SaleOrderResource;
            this._saleOrderNo = this.base_GuestReward.SaleOrderNo;
            this._remark = this.base_GuestReward.Remark;
            this._activedDate = this.base_GuestReward.ActivedDate;
            this._expireDate = this.base_GuestReward.ExpireDate;
            this._reason = this.base_GuestReward.Reason;
            this._status = this.base_GuestReward.Status;
            this._rewardSetupAmount = this.base_GuestReward.RewardSetupAmount;
            this._rewardSetupUnit = this.base_GuestReward.RewardSetupUnit;
            this._sign = this.base_GuestReward.Sign;
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set Entity to PropertyModel</param>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_GuestReward.Id;
            this.GuestId = this.base_GuestReward.GuestId;
            this.RewardId = this.base_GuestReward.RewardId;
            this.Amount = this.base_GuestReward.Amount;
            this.IsApply = this.base_GuestReward.IsApply;
            this.EarnedDate = this.base_GuestReward.EarnedDate;
            this.AppliedDate = this.base_GuestReward.AppliedDate;
            this.RewardValue = this.base_GuestReward.RewardValue;
            this.SaleOrderResource = this.base_GuestReward.SaleOrderResource;
            this.SaleOrderNo = this.base_GuestReward.SaleOrderNo;
            this.Remark = this.base_GuestReward.Remark;
            this.ActivedDate = this.base_GuestReward.ActivedDate;
            this.ExpireDate = this.base_GuestReward.ExpireDate;
            this.Reason = this.base_GuestReward.Reason;
            this.Status = this.base_GuestReward.Status;
            this.RewardSetupAmount = this.base_GuestReward.RewardSetupAmount;
            this.RewardSetupUnit = this.base_GuestReward.RewardSetupUnit;
            this.Sign = this.base_GuestReward.Sign;
        }

        #endregion

        #region Custom Code

        #region Properties
        #region RewardName
        private string _rewardName;
        /// <summary>
        /// Gets or sets the RewardName.
        /// </summary>
        public string RewardName
        {
            get { return _rewardName; }
            set
            {
                if (_rewardName != value)
                {
                    _rewardName = value;
                    OnPropertyChanged(() => RewardName);
                }
            }
        }
        #endregion

        #region TotalAfterReward
        private decimal _totalAfterReward;
        /// <summary>
        /// Gets or sets the TotalAfterReward.
        /// </summary>
        public decimal TotalAfterReward
        {
            get { return _totalAfterReward; }
            set
            {
                if (_totalAfterReward != value)
                {
                    _totalAfterReward = value;
                    OnPropertyChanged(() => TotalAfterReward);
                }
            }
        }
        #endregion

        #region TotalRewardDisplay
        private string _totalRewardDisplay;
        /// <summary>
        /// Gets or sets the TotalRewardDisplay.
        /// </summary>
        public string TotalRewardDisplay
        {
            get { return _totalRewardDisplay; }
            set
            {
                if (_totalRewardDisplay != value)
                {
                    _totalRewardDisplay = value;
                    OnPropertyChanged(() => TotalRewardDisplay);
                }
            }
        }
        #endregion

        #region IsAccepted
        private bool _isAccepted = false;
        /// <summary>
        /// Gets or sets the IsAccepted.
        /// </summary>
        public bool IsAccepted
        {
            get { return _isAccepted; }
            set
            {
                if (_isAccepted != value)
                {
                    _isAccepted = value;
                    OnPropertyChanged(() => IsAccepted);
                }
            }
        }
        #endregion

        #region IsVisibleRowDetail
        private bool _isVisibleRowDetail;
        /// <summary>
        /// Gets or sets the IsVisibleRowDetail.
        /// </summary>
        public bool IsVisibleRowDetail
        {
            get { return _isVisibleRowDetail; }
            set
            {
                if (_isVisibleRowDetail != value)
                {
                    _isVisibleRowDetail = value;
                    OnPropertyChanged(() => IsVisibleRowDetail);
                }
            }
        }
        #endregion

        #region RequireReward
        private string _requireReward = string.Empty;
        /// <summary>
        /// Gets or sets the RequireReward.
        /// </summary>
        public string RequireReward
        {
            get { return _requireReward; }
            set
            {
                if (_requireReward != value)
                {
                    _requireReward = value;
                    OnPropertyChanged(() => RequireReward);
                }
            }
        }
        #endregion

        #region RewardAmount
        private string _rewardAmount;
        /// <summary>
        /// Gets or sets the RewardAmount.
        /// <para>Using for RewardEarnView get from reward amount type</para>
        /// </summary>
        public string RewardAmount
        {
            get { return _rewardAmount; }
            set
            {
                if (_rewardAmount != value)
                {
                    _rewardAmount = value;
                    OnPropertyChanged(() => RewardAmount);
                }
            }
        }
        #endregion

        #region IsExpired
        /// <summary>
        /// Gets the IsNeverExpired.
        /// using for change text color to red for text
        /// </summary>
        public bool IsExpired
        {
            get
            {
                return this.ExpireDate.HasValue ? this.ExpireDate.Value < DateTime.Today : false;
            }

        }
        #endregion


        #endregion

        #region Methods
        public void UpdateModel(base_GuestRewardModel guestRewardModel)
        {
            //this._id = guestRewardModel.Id;
            this._guestId = guestRewardModel.GuestId;
            this._rewardId = guestRewardModel.RewardId;
            this._amount = guestRewardModel.Amount;
            this._isApply = guestRewardModel.IsApply;
            this._earnedDate = guestRewardModel.EarnedDate;
            this._appliedDate = guestRewardModel.AppliedDate;
            this._rewardValue = guestRewardModel.RewardValue;
            this._saleOrderResource = guestRewardModel.SaleOrderResource;
            this._saleOrderNo = guestRewardModel.SaleOrderNo;
            this._remark = guestRewardModel.Remark;
            this._activedDate = guestRewardModel.ActivedDate;
            this._expireDate = guestRewardModel.ExpireDate;
            this._reason = guestRewardModel.Reason;
            this._status = guestRewardModel.Status;

        }

        public base_GuestRewardModel CloneObj()
        {
            return this.MemberwiseClone() as base_GuestRewardModel;
        }
        #endregion

        #region Override
        protected override void PropertyChangedCompleted(string propertyName)
        {
            switch (propertyName)
            {
                case "ExpireDate":
                    OnPropertyChanged(() => IsExpired);
                    break;
            }
        }
        #endregion

        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get
            {
                List<string> errors = new List<string>();
                PropertyDescriptorCollection props = TypeDescriptor.GetProperties(this);
                foreach (PropertyDescriptor prop in props)
                {
                    string msg = this[prop.Name];
                    if (!string.IsNullOrWhiteSpace(msg))
                    {
                        errors.Add(msg);
                    }
                }
                return string.Join(Environment.NewLine, errors);
            }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GuestId":
                        break;
                    case "RewardId":
                        break;
                    case "RewardRedeem":
                        break;
                    case "IsApply":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
