//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_MemberShip
    /// </summary>
    [Serializable]
    public partial class base_MemberShipModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_MemberShipModel()
        {
            this.IsNew = true;
            this.base_MemberShip = new base_MemberShip();
        }

        // Default constructor that set entity to field
        public base_MemberShipModel(base_MemberShip base_membership, bool isRaiseProperties = false)
        {
            this.base_MemberShip = base_membership;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_MemberShip base_MemberShip { get; private set; }

        #endregion

        #region Primitive Properties

        protected long _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public long Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected string _idCard;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IdCard</para>
        /// </summary>
        public string IdCard
        {
            get { return this._idCard; }
            set
            {
                if (this._idCard != value)
                {
                    this.IsDirty = true;
                    this._idCard = value;
                    OnPropertyChanged(() => IdCard);
                    PropertyChangedCompleted(() => IdCard);
                }
            }
        }

        protected byte[] _idCardImg;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IdCardImg</para>
        /// </summary>
        public byte[] IdCardImg
        {
            get { return this._idCardImg; }
            set
            {
                if (this._idCardImg != value)
                {
                    this.IsDirty = true;
                    this._idCardImg = value;
                    OnPropertyChanged(() => IdCardImg);
                    PropertyChangedCompleted(() => IdCardImg);
                }
            }
        }

        protected long _guestId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GuestId</para>
        /// </summary>
        public long GuestId
        {
            get { return this._guestId; }
            set
            {
                if (this._guestId != value)
                {
                    this.IsDirty = true;
                    this._guestId = value;
                    OnPropertyChanged(() => GuestId);
                    PropertyChangedCompleted(() => GuestId);
                }
            }
        }

        protected string _memberType;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the MemberType</para>
        /// </summary>
        public string MemberType
        {
            get { return this._memberType; }
            set
            {
                if (this._memberType != value)
                {
                    this.IsDirty = true;
                    this._memberType = value;
                    OnPropertyChanged(() => MemberType);
                    PropertyChangedCompleted(() => MemberType);
                }
            }
        }

        protected short _status;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Status</para>
        /// </summary>
        public short Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                    OnPropertyChanged(() => Status);
                    PropertyChangedCompleted(() => Status);
                }
            }
        }

        protected bool _isPurged;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsPurged</para>
        /// </summary>
        public bool IsPurged
        {
            get { return this._isPurged; }
            set
            {
                if (this._isPurged != value)
                {
                    this.IsDirty = true;
                    this._isPurged = value;
                    OnPropertyChanged(() => IsPurged);
                    PropertyChangedCompleted(() => IsPurged);
                }
            }
        }

        protected string _userCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserCreated</para>
        /// </summary>
        public string UserCreated
        {
            get { return this._userCreated; }
            set
            {
                if (this._userCreated != value)
                {
                    this.IsDirty = true;
                    this._userCreated = value;
                    OnPropertyChanged(() => UserCreated);
                    PropertyChangedCompleted(() => UserCreated);
                }
            }
        }

        protected string _userUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserUpdated</para>
        /// </summary>
        public string UserUpdated
        {
            get { return this._userUpdated; }
            set
            {
                if (this._userUpdated != value)
                {
                    this.IsDirty = true;
                    this._userUpdated = value;
                    OnPropertyChanged(() => UserUpdated);
                    PropertyChangedCompleted(() => UserUpdated);
                }
            }
        }

        protected System.DateTime _dateCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateCreated</para>
        /// </summary>
        public System.DateTime DateCreated
        {
            get { return this._dateCreated; }
            set
            {
                if (this._dateCreated != value)
                {
                    this.IsDirty = true;
                    this._dateCreated = value;
                    OnPropertyChanged(() => DateCreated);
                    PropertyChangedCompleted(() => DateCreated);
                }
            }
        }

        protected System.DateTime _dateUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateUpdated</para>
        /// </summary>
        public System.DateTime DateUpdated
        {
            get { return this._dateUpdated; }
            set
            {
                if (this._dateUpdated != value)
                {
                    this.IsDirty = true;
                    this._dateUpdated = value;
                    OnPropertyChanged(() => DateUpdated);
                    PropertyChangedCompleted(() => DateUpdated);
                }
            }
        }

        protected string _guestResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GuestResource</para>
        /// </summary>
        public string GuestResource
        {
            get { return this._guestResource; }
            set
            {
                if (this._guestResource != value)
                {
                    this.IsDirty = true;
                    this._guestResource = value;
                    OnPropertyChanged(() => GuestResource);
                    PropertyChangedCompleted(() => GuestResource);
                }
            }
        }

        protected decimal _totalCashReward;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the TotalCashReward</para>
        /// </summary>
        public decimal TotalCashReward
        {
            get { return this._totalCashReward; }
            set
            {
                if (this._totalCashReward != value)
                {
                    this.IsDirty = true;
                    this._totalCashReward = value;
                    OnPropertyChanged(() => TotalCashReward);
                    PropertyChangedCompleted(() => TotalCashReward);
                }
            }
        }

        protected decimal _totalPointReward;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the TotalPointReward</para>
        /// </summary>
        public decimal TotalPointReward
        {
            get { return this._totalPointReward; }
            set
            {
                if (this._totalPointReward != value)
                {
                    this.IsDirty = true;
                    this._totalPointReward = value;
                    OnPropertyChanged(() => TotalPointReward);
                    PropertyChangedCompleted(() => TotalPointReward);
                }
            }
        }

        protected int _totalPercentReward;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the TotalPercentReward</para>
        /// </summary>
        public int TotalPercentReward
        {
            get { return this._totalPercentReward; }
            set
            {
                if (this._totalPercentReward != value)
                {
                    this.IsDirty = true;
                    this._totalPercentReward = value;
                    OnPropertyChanged(() => TotalPercentReward);
                    PropertyChangedCompleted(() => TotalPercentReward);
                }
            }
        }

        protected string _cashRewardCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CashRewardCode</para>
        /// </summary>
        public string CashRewardCode
        {
            get { return this._cashRewardCode; }
            set
            {
                if (this._cashRewardCode != value)
                {
                    this.IsDirty = true;
                    this._cashRewardCode = value;
                    OnPropertyChanged(() => CashRewardCode);
                    PropertyChangedCompleted(() => CashRewardCode);
                }
            }
        }

        protected byte[] _cashRewardImg;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CashRewardImg</para>
        /// </summary>
        public byte[] CashRewardImg
        {
            get { return this._cashRewardImg; }
            set
            {
                if (this._cashRewardImg != value)
                {
                    this.IsDirty = true;
                    this._cashRewardImg = value;
                    OnPropertyChanged(() => CashRewardImg);
                    PropertyChangedCompleted(() => CashRewardImg);
                }
            }
        }

        protected string _pointRewardCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PointRewardCode</para>
        /// </summary>
        public string PointRewardCode
        {
            get { return this._pointRewardCode; }
            set
            {
                if (this._pointRewardCode != value)
                {
                    this.IsDirty = true;
                    this._pointRewardCode = value;
                    OnPropertyChanged(() => PointRewardCode);
                    PropertyChangedCompleted(() => PointRewardCode);
                }
            }
        }

        protected byte[] _pointRewardImg;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PointRewardImg</para>
        /// </summary>
        public byte[] PointRewardImg
        {
            get { return this._pointRewardImg; }
            set
            {
                if (this._pointRewardImg != value)
                {
                    this.IsDirty = true;
                    this._pointRewardImg = value;
                    OnPropertyChanged(() => PointRewardImg);
                    PropertyChangedCompleted(() => PointRewardImg);
                }
            }
        }

        protected string _percentRewardCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PercentRewardCode</para>
        /// </summary>
        public string PercentRewardCode
        {
            get { return this._percentRewardCode; }
            set
            {
                if (this._percentRewardCode != value)
                {
                    this.IsDirty = true;
                    this._percentRewardCode = value;
                    OnPropertyChanged(() => PercentRewardCode);
                    PropertyChangedCompleted(() => PercentRewardCode);
                }
            }
        }

        protected byte[] _percentRewardImg;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PercentRewardImg</para>
        /// </summary>
        public byte[] PercentRewardImg
        {
            get { return this._percentRewardImg; }
            set
            {
                if (this._percentRewardImg != value)
                {
                    this.IsDirty = true;
                    this._percentRewardImg = value;
                    OnPropertyChanged(() => PercentRewardImg);
                    PropertyChangedCompleted(() => PercentRewardImg);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_MemberShip.Id = this.Id;
            this.base_MemberShip.IdCard = this.IdCard;
            this.base_MemberShip.IdCardImg = this.IdCardImg;
            this.base_MemberShip.GuestId = this.GuestId;
            this.base_MemberShip.MemberType = this.MemberType;
            this.base_MemberShip.Status = this.Status;
            this.base_MemberShip.IsPurged = this.IsPurged;
            this.base_MemberShip.UserCreated = this.UserCreated;
            this.base_MemberShip.UserUpdated = this.UserUpdated;
            this.base_MemberShip.DateCreated = this.DateCreated;
            this.base_MemberShip.DateUpdated = this.DateUpdated;
            this.base_MemberShip.GuestResource = this.GuestResource;
            this.base_MemberShip.TotalCashReward = this.TotalCashReward;
            this.base_MemberShip.TotalPointReward = this.TotalPointReward;
            this.base_MemberShip.TotalPercentReward = this.TotalPercentReward;
            this.base_MemberShip.CashRewardCode = this.CashRewardCode;
            this.base_MemberShip.CashRewardImg = this.CashRewardImg;
            this.base_MemberShip.PointRewardCode = this.PointRewardCode;
            this.base_MemberShip.PointRewardImg = this.PointRewardImg;
            this.base_MemberShip.PercentRewardCode = this.PercentRewardCode;
            this.base_MemberShip.PercentRewardImg = this.PercentRewardImg;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_MemberShip.Id;
            this._idCard = this.base_MemberShip.IdCard;
            this._idCardImg = this.base_MemberShip.IdCardImg;
            this._guestId = this.base_MemberShip.GuestId;
            this._memberType = this.base_MemberShip.MemberType;
            this._status = this.base_MemberShip.Status;
            this._isPurged = this.base_MemberShip.IsPurged;
            this._userCreated = this.base_MemberShip.UserCreated;
            this._userUpdated = this.base_MemberShip.UserUpdated;
            this._dateCreated = this.base_MemberShip.DateCreated;
            this._dateUpdated = this.base_MemberShip.DateUpdated;
            this._guestResource = this.base_MemberShip.GuestResource;
            this._totalCashReward = this.base_MemberShip.TotalCashReward;
            this._totalPointReward = this.base_MemberShip.TotalPointReward;
            this._totalPercentReward = this.base_MemberShip.TotalPercentReward;
            this._cashRewardCode = this.base_MemberShip.CashRewardCode;
            this._cashRewardImg = this.base_MemberShip.CashRewardImg;
            this._pointRewardCode = this.base_MemberShip.PointRewardCode;
            this._pointRewardImg = this.base_MemberShip.PointRewardImg;
            this._percentRewardCode = this.base_MemberShip.PercentRewardCode;
            this._percentRewardImg = this.base_MemberShip.PercentRewardImg;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_MemberShip.Id;
            this.IdCard = this.base_MemberShip.IdCard;
            this.IdCardImg = this.base_MemberShip.IdCardImg;
            this.GuestId = this.base_MemberShip.GuestId;
            this.MemberType = this.base_MemberShip.MemberType;
            this.Status = this.base_MemberShip.Status;
            this.IsPurged = this.base_MemberShip.IsPurged;
            this.UserCreated = this.base_MemberShip.UserCreated;
            this.UserUpdated = this.base_MemberShip.UserUpdated;
            this.DateCreated = this.base_MemberShip.DateCreated;
            this.DateUpdated = this.base_MemberShip.DateUpdated;
            this.GuestResource = this.base_MemberShip.GuestResource;
            this.TotalCashReward = this.base_MemberShip.TotalCashReward;
            this.TotalPointReward = this.base_MemberShip.TotalPointReward;
            this.TotalPercentReward = this.base_MemberShip.TotalPercentReward;
            this.CashRewardCode = this.base_MemberShip.CashRewardCode;
            this.CashRewardImg = this.base_MemberShip.CashRewardImg;
            this.PointRewardCode = this.base_MemberShip.PointRewardCode;
            this.PointRewardImg = this.base_MemberShip.PointRewardImg;
            this.PercentRewardCode = this.base_MemberShip.PercentRewardCode;
            this.PercentRewardImg = this.base_MemberShip.PercentRewardImg;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GuestId":
                        break;
                    case "MemberType":
                        break;
                    case "CardNumber":
                        break;
                    case "Status":
                        break;
                    case "IsPurged":
                        break;
                    case "UserCreated":
                        break;
                    case "UserUpdated":
                        break;
                    case "DateCreated":
                        break;
                    case "DateUpdated":
                        break;
                    case "Code":
                        break;
                    case "TotalRewardRedeemed":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
