//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_GuestReward
    /// </summary>
    [Serializable]
    public partial class base_GuestRewardModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_GuestRewardModel()
        {
            this.IsNew = true;
            this.base_GuestReward = new base_GuestReward();
        }

        // Default constructor that set entity to field
        public base_GuestRewardModel(base_GuestReward base_guestreward, bool isRaiseProperties = false)
        {
            this.base_GuestReward = base_guestreward;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_GuestReward base_GuestReward { get; private set; }

        #endregion

        #region Primitive Properties

        protected long _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public long Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected long _guestId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GuestId</para>
        /// </summary>
        public long GuestId
        {
            get { return this._guestId; }
            set
            {
                if (this._guestId != value)
                {
                    this.IsDirty = true;
                    this._guestId = value;
                    OnPropertyChanged(() => GuestId);
                    PropertyChangedCompleted(() => GuestId);
                }
            }
        }

        protected int _rewardId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the RewardId</para>
        /// </summary>
        public int RewardId
        {
            get { return this._rewardId; }
            set
            {
                if (this._rewardId != value)
                {
                    this.IsDirty = true;
                    this._rewardId = value;
                    OnPropertyChanged(() => RewardId);
                    PropertyChangedCompleted(() => RewardId);
                }
            }
        }

        protected decimal _amount;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Amount</para>
        /// </summary>
        public decimal Amount
        {
            get { return this._amount; }
            set
            {
                if (this._amount != value)
                {
                    this.IsDirty = true;
                    this._amount = value;
                    OnPropertyChanged(() => Amount);
                    PropertyChangedCompleted(() => Amount);
                }
            }
        }

        protected bool _isApply;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsApply</para>
        /// </summary>
        public bool IsApply
        {
            get { return this._isApply; }
            set
            {
                if (this._isApply != value)
                {
                    this.IsDirty = true;
                    this._isApply = value;
                    OnPropertyChanged(() => IsApply);
                    PropertyChangedCompleted(() => IsApply);
                }
            }
        }

        protected Nullable<System.DateTime> _earnedDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the EarnedDate</para>
        /// </summary>
        public Nullable<System.DateTime> EarnedDate
        {
            get { return this._earnedDate; }
            set
            {
                if (this._earnedDate != value)
                {
                    this.IsDirty = true;
                    this._earnedDate = value;
                    OnPropertyChanged(() => EarnedDate);
                    PropertyChangedCompleted(() => EarnedDate);
                }
            }
        }

        protected Nullable<System.DateTime> _appliedDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the AppliedDate</para>
        /// </summary>
        public Nullable<System.DateTime> AppliedDate
        {
            get { return this._appliedDate; }
            set
            {
                if (this._appliedDate != value)
                {
                    this.IsDirty = true;
                    this._appliedDate = value;
                    OnPropertyChanged(() => AppliedDate);
                    PropertyChangedCompleted(() => AppliedDate);
                }
            }
        }

        protected decimal _rewardValue;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the RewardValue</para>
        /// </summary>
        public decimal RewardValue
        {
            get { return this._rewardValue; }
            set
            {
                if (this._rewardValue != value)
                {
                    this.IsDirty = true;
                    this._rewardValue = value;
                    OnPropertyChanged(() => RewardValue);
                    PropertyChangedCompleted(() => RewardValue);
                }
            }
        }

        protected string _saleOrderResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SaleOrderResource</para>
        /// </summary>
        public string SaleOrderResource
        {
            get { return this._saleOrderResource; }
            set
            {
                if (this._saleOrderResource != value)
                {
                    this.IsDirty = true;
                    this._saleOrderResource = value;
                    OnPropertyChanged(() => SaleOrderResource);
                    PropertyChangedCompleted(() => SaleOrderResource);
                }
            }
        }

        protected string _saleOrderNo;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SaleOrderNo</para>
        /// </summary>
        public string SaleOrderNo
        {
            get { return this._saleOrderNo; }
            set
            {
                if (this._saleOrderNo != value)
                {
                    this.IsDirty = true;
                    this._saleOrderNo = value;
                    OnPropertyChanged(() => SaleOrderNo);
                    PropertyChangedCompleted(() => SaleOrderNo);
                }
            }
        }

        protected string _remark;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Remark</para>
        /// </summary>
        public string Remark
        {
            get { return this._remark; }
            set
            {
                if (this._remark != value)
                {
                    this.IsDirty = true;
                    this._remark = value;
                    OnPropertyChanged(() => Remark);
                    PropertyChangedCompleted(() => Remark);
                }
            }
        }

        protected Nullable<System.DateTime> _activedDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ActivedDate</para>
        /// </summary>
        public Nullable<System.DateTime> ActivedDate
        {
            get { return this._activedDate; }
            set
            {
                if (this._activedDate != value)
                {
                    this.IsDirty = true;
                    this._activedDate = value;
                    OnPropertyChanged(() => ActivedDate);
                    PropertyChangedCompleted(() => ActivedDate);
                }
            }
        }

        protected Nullable<System.DateTime> _expireDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ExpireDate</para>
        /// </summary>
        public Nullable<System.DateTime> ExpireDate
        {
            get { return this._expireDate; }
            set
            {
                if (this._expireDate != value)
                {
                    this.IsDirty = true;
                    this._expireDate = value;
                    OnPropertyChanged(() => ExpireDate);
                    PropertyChangedCompleted(() => ExpireDate);
                }
            }
        }

        protected string _reason;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Reason</para>
        /// </summary>
        public string Reason
        {
            get { return this._reason; }
            set
            {
                if (this._reason != value)
                {
                    this.IsDirty = true;
                    this._reason = value;
                    OnPropertyChanged(() => Reason);
                    PropertyChangedCompleted(() => Reason);
                }
            }
        }

        protected Nullable<short> _status;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Status</para>
        /// </summary>
        public Nullable<short> Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                    OnPropertyChanged(() => Status);
                    PropertyChangedCompleted(() => Status);
                }
            }
        }

        protected decimal _rewardSetupAmount;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the RewardSetupAmount</para>
        /// </summary>
        public decimal RewardSetupAmount
        {
            get { return this._rewardSetupAmount; }
            set
            {
                if (this._rewardSetupAmount != value)
                {
                    this.IsDirty = true;
                    this._rewardSetupAmount = value;
                    OnPropertyChanged(() => RewardSetupAmount);
                    PropertyChangedCompleted(() => RewardSetupAmount);
                }
            }
        }

        protected short _rewardSetupUnit;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the RewardSetupUnit</para>
        /// </summary>
        public short RewardSetupUnit
        {
            get { return this._rewardSetupUnit; }
            set
            {
                if (this._rewardSetupUnit != value)
                {
                    this.IsDirty = true;
                    this._rewardSetupUnit = value;
                    OnPropertyChanged(() => RewardSetupUnit);
                    PropertyChangedCompleted(() => RewardSetupUnit);
                }
            }
        }

        protected string _sign;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Sign</para>
        /// </summary>
        public string Sign
        {
            get { return this._sign; }
            set
            {
                if (this._sign != value)
                {
                    this.IsDirty = true;
                    this._sign = value;
                    OnPropertyChanged(() => Sign);
                    PropertyChangedCompleted(() => Sign);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_GuestReward.Id = this.Id;
            this.base_GuestReward.GuestId = this.GuestId;
            this.base_GuestReward.RewardId = this.RewardId;
            this.base_GuestReward.Amount = this.Amount;
            this.base_GuestReward.IsApply = this.IsApply;
            this.base_GuestReward.EarnedDate = this.EarnedDate;
            this.base_GuestReward.AppliedDate = this.AppliedDate;
            this.base_GuestReward.RewardValue = this.RewardValue;
            this.base_GuestReward.SaleOrderResource = this.SaleOrderResource;
            this.base_GuestReward.SaleOrderNo = this.SaleOrderNo;
            this.base_GuestReward.Remark = this.Remark;
            this.base_GuestReward.ActivedDate = this.ActivedDate;
            this.base_GuestReward.ExpireDate = this.ExpireDate;
            this.base_GuestReward.Reason = this.Reason;
            this.base_GuestReward.Status = this.Status;
            this.base_GuestReward.RewardSetupAmount = this.RewardSetupAmount;
            this.base_GuestReward.RewardSetupUnit = this.RewardSetupUnit;
            this.base_GuestReward.Sign = this.Sign;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_GuestReward.Id;
            this._guestId = this.base_GuestReward.GuestId;
            this._rewardId = this.base_GuestReward.RewardId;
            this._amount = this.base_GuestReward.Amount;
            this._isApply = this.base_GuestReward.IsApply;
            this._earnedDate = this.base_GuestReward.EarnedDate;
            this._appliedDate = this.base_GuestReward.AppliedDate;
            this._rewardValue = this.base_GuestReward.RewardValue;
            this._saleOrderResource = this.base_GuestReward.SaleOrderResource;
            this._saleOrderNo = this.base_GuestReward.SaleOrderNo;
            this._remark = this.base_GuestReward.Remark;
            this._activedDate = this.base_GuestReward.ActivedDate;
            this._expireDate = this.base_GuestReward.ExpireDate;
            this._reason = this.base_GuestReward.Reason;
            this._status = this.base_GuestReward.Status;
            this._rewardSetupAmount = this.base_GuestReward.RewardSetupAmount;
            this._rewardSetupUnit = this.base_GuestReward.RewardSetupUnit;
            this._sign = this.base_GuestReward.Sign;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_GuestReward.Id;
            this.GuestId = this.base_GuestReward.GuestId;
            this.RewardId = this.base_GuestReward.RewardId;
            this.Amount = this.base_GuestReward.Amount;
            this.IsApply = this.base_GuestReward.IsApply;
            this.EarnedDate = this.base_GuestReward.EarnedDate;
            this.AppliedDate = this.base_GuestReward.AppliedDate;
            this.RewardValue = this.base_GuestReward.RewardValue;
            this.SaleOrderResource = this.base_GuestReward.SaleOrderResource;
            this.SaleOrderNo = this.base_GuestReward.SaleOrderNo;
            this.Remark = this.base_GuestReward.Remark;
            this.ActivedDate = this.base_GuestReward.ActivedDate;
            this.ExpireDate = this.base_GuestReward.ExpireDate;
            this.Reason = this.base_GuestReward.Reason;
            this.Status = this.base_GuestReward.Status;
            this.RewardSetupAmount = this.base_GuestReward.RewardSetupAmount;
            this.RewardSetupUnit = this.base_GuestReward.RewardSetupUnit;
            this.Sign = this.base_GuestReward.Sign;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GuestId":
                        break;
                    case "RewardId":
                        break;
                    case "Amount":
                        break;
                    case "IsApply":
                        break;
                    case "EarnedDate":
                        break;
                    case "AppliedDate":
                        break;
                    case "RewardValue":
                        break;
                    case "SaleOrderResource":
                        break;
                    case "SaleOrderNo":
                        break;
                    case "Remark":
                        break;
                    case "ActivedDate":
                        break;
                    case "ExpireDate":
                        break;
                    case "Reason":
                        break;
                    case "Status":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
