//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_LayawayManager
    /// </summary>
    [Serializable]
    public partial class base_LayawayManagerModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_LayawayManagerModel()
        {
            this.IsNew = true;
            this.base_LayawayManager = new base_LayawayManager();
        }

        // Default constructor that set entity to field
        public base_LayawayManagerModel(base_LayawayManager base_layawaymanager, bool isRaiseProperties = false)
        {
            this.base_LayawayManager = base_layawaymanager;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_LayawayManager base_LayawayManager { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected string _name;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Name</para>
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set
            {
                if (this._name != value)
                {
                    this.IsDirty = true;
                    this._name = value;
                    OnPropertyChanged(() => Name);
                    PropertyChangedCompleted(() => Name);
                }
            }
        }

        protected decimal _deposit;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Deposit</para>
        /// </summary>
        public decimal Deposit
        {
            get { return this._deposit; }
            set
            {
                if (this._deposit != value)
                {
                    this.IsDirty = true;
                    this._deposit = value;
                    OnPropertyChanged(() => Deposit);
                    PropertyChangedCompleted(() => Deposit);
                }
            }
        }

        protected short _depositUnit;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DepositUnit</para>
        /// </summary>
        public short DepositUnit
        {
            get { return this._depositUnit; }
            set
            {
                if (this._depositUnit != value)
                {
                    this.IsDirty = true;
                    this._depositUnit = value;
                    OnPropertyChanged(() => DepositUnit);
                    PropertyChangedCompleted(() => DepositUnit);
                }
            }
        }

        protected int _term;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Term</para>
        /// </summary>
        public int Term
        {
            get { return this._term; }
            set
            {
                if (this._term != value)
                {
                    this.IsDirty = true;
                    this._term = value;
                    OnPropertyChanged(() => Term);
                    PropertyChangedCompleted(() => Term);
                }
            }
        }

        protected Nullable<int> _paymentSchedule;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PaymentSchedule</para>
        /// </summary>
        public Nullable<int> PaymentSchedule
        {
            get { return this._paymentSchedule; }
            set
            {
                if (this._paymentSchedule != value)
                {
                    this.IsDirty = true;
                    this._paymentSchedule = value;
                    OnPropertyChanged(() => PaymentSchedule);
                    PropertyChangedCompleted(() => PaymentSchedule);
                }
            }
        }

        protected Nullable<short> _paymentScheduleType;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PaymentScheduleType</para>
        /// </summary>
        public Nullable<short> PaymentScheduleType
        {
            get { return this._paymentScheduleType; }
            set
            {
                if (this._paymentScheduleType != value)
                {
                    this.IsDirty = true;
                    this._paymentScheduleType = value;
                    OnPropertyChanged(() => PaymentScheduleType);
                    PropertyChangedCompleted(() => PaymentScheduleType);
                }
            }
        }

        protected decimal _fee;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Fee</para>
        /// </summary>
        public decimal Fee
        {
            get { return this._fee; }
            set
            {
                if (this._fee != value)
                {
                    this.IsDirty = true;
                    this._fee = value;
                    OnPropertyChanged(() => Fee);
                    PropertyChangedCompleted(() => Fee);
                }
            }
        }

        protected short _feeUnit;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the FeeUnit</para>
        /// </summary>
        public short FeeUnit
        {
            get { return this._feeUnit; }
            set
            {
                if (this._feeUnit != value)
                {
                    this.IsDirty = true;
                    this._feeUnit = value;
                    OnPropertyChanged(() => FeeUnit);
                    PropertyChangedCompleted(() => FeeUnit);
                }
            }
        }

        protected decimal _openFee;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the OpenFee</para>
        /// </summary>
        public decimal OpenFee
        {
            get { return this._openFee; }
            set
            {
                if (this._openFee != value)
                {
                    this.IsDirty = true;
                    this._openFee = value;
                    OnPropertyChanged(() => OpenFee);
                    PropertyChangedCompleted(() => OpenFee);
                }
            }
        }

        protected decimal _cancellationFee;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CancellationFee</para>
        /// </summary>
        public decimal CancellationFee
        {
            get { return this._cancellationFee; }
            set
            {
                if (this._cancellationFee != value)
                {
                    this.IsDirty = true;
                    this._cancellationFee = value;
                    OnPropertyChanged(() => CancellationFee);
                    PropertyChangedCompleted(() => CancellationFee);
                }
            }
        }

        protected short _cancellationUnit;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CancellationUnit</para>
        /// </summary>
        public short CancellationUnit
        {
            get { return this._cancellationUnit; }
            set
            {
                if (this._cancellationUnit != value)
                {
                    this.IsDirty = true;
                    this._cancellationUnit = value;
                    OnPropertyChanged(() => CancellationUnit);
                    PropertyChangedCompleted(() => CancellationUnit);
                }
            }
        }

        protected decimal _minimumPurchase;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the MinimumPurchase</para>
        /// </summary>
        public decimal MinimumPurchase
        {
            get { return this._minimumPurchase; }
            set
            {
                if (this._minimumPurchase != value)
                {
                    this.IsDirty = true;
                    this._minimumPurchase = value;
                    OnPropertyChanged(() => MinimumPurchase);
                    PropertyChangedCompleted(() => MinimumPurchase);
                }
            }
        }

        protected decimal _lateFee;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the LateFee</para>
        /// </summary>
        public decimal LateFee
        {
            get { return this._lateFee; }
            set
            {
                if (this._lateFee != value)
                {
                    this.IsDirty = true;
                    this._lateFee = value;
                    OnPropertyChanged(() => LateFee);
                    PropertyChangedCompleted(() => LateFee);
                }
            }
        }

        protected short _status;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Status</para>
        /// </summary>
        public short Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                    OnPropertyChanged(() => Status);
                    PropertyChangedCompleted(() => Status);
                }
            }
        }

        protected System.DateTime _dateCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateCreated</para>
        /// </summary>
        public System.DateTime DateCreated
        {
            get { return this._dateCreated; }
            set
            {
                if (this._dateCreated != value)
                {
                    this.IsDirty = true;
                    this._dateCreated = value;
                    OnPropertyChanged(() => DateCreated);
                    PropertyChangedCompleted(() => DateCreated);
                }
            }
        }

        protected string _userCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserCreated</para>
        /// </summary>
        public string UserCreated
        {
            get { return this._userCreated; }
            set
            {
                if (this._userCreated != value)
                {
                    this.IsDirty = true;
                    this._userCreated = value;
                    OnPropertyChanged(() => UserCreated);
                    PropertyChangedCompleted(() => UserCreated);
                }
            }
        }

        protected System.DateTime _dateUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateUpdated</para>
        /// </summary>
        public System.DateTime DateUpdated
        {
            get { return this._dateUpdated; }
            set
            {
                if (this._dateUpdated != value)
                {
                    this.IsDirty = true;
                    this._dateUpdated = value;
                    OnPropertyChanged(() => DateUpdated);
                    PropertyChangedCompleted(() => DateUpdated);
                }
            }
        }

        protected string _userUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserUpdated</para>
        /// </summary>
        public string UserUpdated
        {
            get { return this._userUpdated; }
            set
            {
                if (this._userUpdated != value)
                {
                    this.IsDirty = true;
                    this._userUpdated = value;
                    OnPropertyChanged(() => UserUpdated);
                    PropertyChangedCompleted(() => UserUpdated);
                }
            }
        }

        protected System.Guid _resource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Resource</para>
        /// </summary>
        public System.Guid Resource
        {
            get { return this._resource; }
            set
            {
                if (this._resource != value)
                {
                    this.IsDirty = true;
                    this._resource = value;
                    OnPropertyChanged(() => Resource);
                    PropertyChangedCompleted(() => Resource);
                }
            }
        }

        protected string _reasonReActive;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ReasonReActive</para>
        /// </summary>
        public string ReasonReActive
        {
            get { return this._reasonReActive; }
            set
            {
                if (this._reasonReActive != value)
                {
                    this.IsDirty = true;
                    this._reasonReActive = value;
                    OnPropertyChanged(() => ReasonReActive);
                    PropertyChangedCompleted(() => ReasonReActive);
                }
            }
        }

        protected Nullable<System.DateTime> _startDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the StartDate</para>
        /// </summary>
        public Nullable<System.DateTime> StartDate
        {
            get { return this._startDate; }
            set
            {
                if (this._startDate != value)
                {
                    this.IsDirty = true;
                    this._startDate = value;
                    OnPropertyChanged(() => StartDate);
                    PropertyChangedCompleted(() => StartDate);
                }
            }
        }

        protected Nullable<System.DateTime> _endDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the EndDate</para>
        /// </summary>
        public Nullable<System.DateTime> EndDate
        {
            get { return this._endDate; }
            set
            {
                if (this._endDate != value)
                {
                    this.IsDirty = true;
                    this._endDate = value;
                    OnPropertyChanged(() => EndDate);
                    PropertyChangedCompleted(() => EndDate);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_LayawayManager.Id = this.Id;
            this.base_LayawayManager.Name = this.Name;
            this.base_LayawayManager.Deposit = this.Deposit;
            this.base_LayawayManager.DepositUnit = this.DepositUnit;
            this.base_LayawayManager.Term = this.Term;
            this.base_LayawayManager.PaymentSchedule = this.PaymentSchedule;
            this.base_LayawayManager.PaymentScheduleType = this.PaymentScheduleType;
            this.base_LayawayManager.Fee = this.Fee;
            this.base_LayawayManager.FeeUnit = this.FeeUnit;
            this.base_LayawayManager.OpenFee = this.OpenFee;
            this.base_LayawayManager.CancellationFee = this.CancellationFee;
            this.base_LayawayManager.CancellationUnit = this.CancellationUnit;
            this.base_LayawayManager.MinimumPurchase = this.MinimumPurchase;
            this.base_LayawayManager.LateFee = this.LateFee;
            this.base_LayawayManager.Status = this.Status;
            this.base_LayawayManager.DateCreated = this.DateCreated;
            this.base_LayawayManager.UserCreated = this.UserCreated;
            this.base_LayawayManager.DateUpdated = this.DateUpdated;
            this.base_LayawayManager.UserUpdated = this.UserUpdated;
            this.base_LayawayManager.Resource = this.Resource;
            this.base_LayawayManager.ReasonReActive = this.ReasonReActive;
            this.base_LayawayManager.StartDate = this.StartDate;
            this.base_LayawayManager.EndDate = this.EndDate;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_LayawayManager.Id;
            this._name = this.base_LayawayManager.Name;
            this._deposit = this.base_LayawayManager.Deposit;
            this._depositUnit = this.base_LayawayManager.DepositUnit;
            this._term = this.base_LayawayManager.Term;
            this._paymentSchedule = this.base_LayawayManager.PaymentSchedule;
            this._paymentScheduleType = this.base_LayawayManager.PaymentScheduleType;
            this._fee = this.base_LayawayManager.Fee;
            this._feeUnit = this.base_LayawayManager.FeeUnit;
            this._openFee = this.base_LayawayManager.OpenFee;
            this._cancellationFee = this.base_LayawayManager.CancellationFee;
            this._cancellationUnit = this.base_LayawayManager.CancellationUnit;
            this._minimumPurchase = this.base_LayawayManager.MinimumPurchase;
            this._lateFee = this.base_LayawayManager.LateFee;
            this._status = this.base_LayawayManager.Status;
            this._dateCreated = this.base_LayawayManager.DateCreated;
            this._userCreated = this.base_LayawayManager.UserCreated;
            this._dateUpdated = this.base_LayawayManager.DateUpdated;
            this._userUpdated = this.base_LayawayManager.UserUpdated;
            this._resource = this.base_LayawayManager.Resource;
            this._reasonReActive = this.base_LayawayManager.ReasonReActive;
            this._startDate = this.base_LayawayManager.StartDate;
            this._endDate = this.base_LayawayManager.EndDate;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_LayawayManager.Id;
            this.Name = this.base_LayawayManager.Name;
            this.Deposit = this.base_LayawayManager.Deposit;
            this.DepositUnit = this.base_LayawayManager.DepositUnit;
            this.Term = this.base_LayawayManager.Term;
            this.PaymentSchedule = this.base_LayawayManager.PaymentSchedule;
            this.PaymentScheduleType = this.base_LayawayManager.PaymentScheduleType;
            this.Fee = this.base_LayawayManager.Fee;
            this.FeeUnit = this.base_LayawayManager.FeeUnit;
            this.OpenFee = this.base_LayawayManager.OpenFee;
            this.CancellationFee = this.base_LayawayManager.CancellationFee;
            this.CancellationUnit = this.base_LayawayManager.CancellationUnit;
            this.MinimumPurchase = this.base_LayawayManager.MinimumPurchase;
            this.LateFee = this.base_LayawayManager.LateFee;
            this.Status = this.base_LayawayManager.Status;
            this.DateCreated = this.base_LayawayManager.DateCreated;
            this.UserCreated = this.base_LayawayManager.UserCreated;
            this.DateUpdated = this.base_LayawayManager.DateUpdated;
            this.UserUpdated = this.base_LayawayManager.UserUpdated;
            this.Resource = this.base_LayawayManager.Resource;
            this.ReasonReActive = this.base_LayawayManager.ReasonReActive;
            this.StartDate = this.base_LayawayManager.StartDate;
            this.EndDate = this.base_LayawayManager.EndDate;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "Name":
                        break;
                    case "Deposit":
                        break;
                    case "DepositUnit":
                        break;
                    case "Term":
                        break;
                    case "PaymentSchedule":
                        break;
                    case "PaymentScheduleType":
                        break;
                    case "Fee":
                        break;
                    case "FeeUnit":
                        break;
                    case "OpenFee":
                        break;
                    case "CancellationFee":
                        break;
                    case "CancellationUnit":
                        break;
                    case "MinimumPurchase":
                        break;
                    case "LateFee":
                        break;
                    case "Status":
                        break;
                    case "DateCreated":
                        break;
                    case "UserCreated":
                        break;
                    case "DateUpdated":
                        break;
                    case "UserUpdated":
                        break;
                    case "Resource":
                        break;
                    case "ReasonReActive":
                        break;
                    case "StartDate":
                        break;
                    case "EndDate":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
