//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.Toolkit.Base;


namespace CPC.POS.Model
{
    /// <summary>
    /// Model for table LOP
    /// </summary>
    [Serializable]
    public partial class ImportCustomerModel : ModelBase
    {
        #region Constructor

        // Default constructor
        public ImportCustomerModel()
        {
           
        }

        #endregion

        #region Primitive Properties

        protected int _customerID;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CustomerID</para>
        /// </summary>
        public int CustomerID
        {
            get { return this._customerID; }
            set
            {
                if (this._customerID != value)
                {
                    this._customerID = value;
                    OnPropertyChanged(() => CustomerID);
                   
                }
            }
        }

        protected string _customerName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CustomerName</para>
        /// </summary>
        public string CustomerName
        {
            get { return this._customerName; }
            set
            {
                if (this._customerName != value)
                {
                    this._customerName = value;
                     OnPropertyChanged(() => CustomerName);
                }
            }
        }

        protected string _city;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the City</para>
        /// </summary>
        public string City
        {
            get { return this._city; }
            set
            {
                if (this._city != value)
                {
                    this._city = value;
                         OnPropertyChanged(() => City);
                }
            }
        }

        protected string _street;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Street</para>
        /// </summary>
        public string Street
        {
            get { return this._street; }
            set
            {
                if (this._street != value)
                {
                    this._street = value;
                      OnPropertyChanged(() => Street);
                }
            }
        }

        protected string _address;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Address</para>
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set
            {
                if (this._address != value)
                {
                    this._address = value;
                     OnPropertyChanged(() => Address);
                }
            }
        }

        protected string _phone;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Phone</para>
        /// </summary>
        public string Phone
        {
            get { return this._phone; }
            set
            {
                if (this._phone != value)
                {
                    this._phone = value;
                    OnPropertyChanged(() => Phone);
                }
            }
        }

        protected string _cellPhone;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Makhoa</para>
        /// </summary>
        public string CellPhone
        {
            get { return this._cellPhone; }
            set
            {
                if (this._cellPhone != value)
                {
                    this._cellPhone = value;
                    OnPropertyChanged(() => CellPhone);
                }
            }
        }

        #endregion

        
    }
}
